src/app/00043-CuentasPorCobrar/WebApp/ViewModels/PeriodoViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WebApp.ViewModels
{
    public class PeriodoViewModel
    {
        public int I_PeriodoID { get; set; }
        public string T_TipoPerDesc { get; set; }
        public short? I_Anio { get; set; }
        public DateTime? D_FecVencto { get; set; }
        public short? I_Prioridad { get; set; }
    }

    public class MantenimientoPeriodoViewModel
    {
        public int? I_PeriodoID { get; set; }

        [Display(Name = "Descripción")]
        public int I_TipoPeriodoID { get; set; }

        [Display(Name = "Año")]
        public short? I_Anio { get; set; }

        [Display(Name = "Fch. Vencimiento")]
        public DateTime? D_FecVencto { get; set; }

        [Display(Name = "Prioridad")]
        public byte? I_Prioridad { get; set; }

        [Display(Name = "Nro de Cta.Cte")]
        public int[] Arr_CtaDepositoID { get; set; }

        public bool? B_Habilitado { get; set; }
    }
}

src/app/00043-CuentasPorCobrar/WebApp/Controllers/PeriodosController.cs
using Domain.DTO;
using Domain.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApp.Models;
using WebApp.ViewModels;
using WebMatrix.WebData;

namespace WebApp.Controllers
{
    public class PeriodosController : Controller
    {
        PeriodoModel periodoModel;

        public PeriodosController()
        {
            periodoModel = new PeriodoModel();
        }

        public ActionResult Index()
        {
            ViewBag.Title = "Desc. Cuota de Pago";

            var lista = periodoModel.Listar_Periodos_Habilitados();

            return View(lista);
        }

        public ActionResult Create()
        {
            ViewBag.Title = "Nuevo registro";

            Cargar_Listas();

            ViewBag.Lista_CtaDepoHabilitadas = new List<SelectViewModel>();

            ViewBag.Lista_CtaDepoPeriodo = new List<SelectViewModel>();

            return PartialView("_MantenimientoPeriodo");
        }

        public ActionResult Edit(int id)
        {
            ViewBag.Title = "Editar registro";

            Cargar_Listas();

            var model = periodoModel.Obtener_Periodo(id);

            ViewBag.Lista_CtaDepoHabilitadas = periodoModel.Listar_Combo_CtaDepositoHabilitadas(model.I_TipoPeriodoID);

            ViewBag.Lista_CtaDepoPeriodo = periodoModel.Listar_Combo_CtasDepoPeriodo(id);

            return PartialView("_MantenimientoPeriodo", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save(MantenimientoPeriodoViewModel model)
        {
            Response result = new Response();

            if (ModelState.IsValid)
            {
                result = periodoModel.Grabar_Periodo(model, WebSecurity.CurrentUserId);
            }
            else
            {
                string details = "";

                foreach (ModelState modelState in ViewData.ModelState.Values)
                {
                    foreach (ModelError error in modelState.Errors)
                    {
                        details += error.ErrorMessage + " / ";
                    }
                }

                ResponseModel.Error(result, "Ha ocurrido un error con el envio de datos" + details);
            }

            return PartialView("_MsgPartialWR", result);
        }

        private void Cargar_Listas()
        {
            ViewBag.Lista_TipoPeriodo = periodoModel.Listar_Combo_TipoPeriodo();

            ViewBag.Lista_Anios = periodoModel.Listar_Anios();
        }
    }
}

src/app/00043-CuentasPorCobrar/WebApp/Views/Periodos/Index.cshtml
@model IEnumerable<WebApp.ViewModels.PeriodoViewModel>

@using GridMvc.Html

<div class="container-fluid">
    <div class="col-12">
        <section class="content-header">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb float-right small d-none d-sm-inline-flex">
                    <li class="breadcrumb-item"><a href="@Url.Action("Index", "Home")"><i class="fa fa-home">&nbsp;</i>Inicio</a></li>
                    <li class="breadcrumb-item"><span><i class="fa fa-wrench">&nbsp;</i>Mantenimiento </span></li>
                    <li class="breadcrumb-item active"><span><i class="fa fa-envelope">&nbsp;</i>@ViewBag.Title </span></li>
                </ol>
            </nav>
            <h1 class="">@ViewBag.Title <small></small></h1>
        </section>
    </div>
    <br />

    <div class="col-12">
        <a href="@Url.Action("Create", "Periodos")" class="btn btn-primary pull-right modal-link">
            <i class="fa fa-envelope"></i> Nuevo
        </a>

        <p class="h3"><small>Desc. Cuota de pago</small></p>
        <br />

        <br />
        <div class="table-responsive" style="min-height:300px">
            @Html.Grid(Model).Columns(columns =>
                {
                    columns.Add(c => c.T_TipoPerDesc).Titled("Descripción").Filterable(true);
                    columns.Add(c => c.I_Anio).Titled("Año").Filterable(true);
                    columns.Add(c => c.D_FecVencto).Format("{0:dd/MM/yyyy}").Titled("Fch. Vencimiento").Filterable(true);
                    columns.Add(c => c.I_Prioridad).Titled("Prioridad").Filterable(true);
                    columns.Add().SetWidth(200).Css("text-right").Encoded(false).Sanitized(false).
                        RenderValueAs(model => @<a href="@Url.Action("Edit", "Periodos", new { id = model.I_PeriodoID })" class="modal-link"><i class="fa fa-pencil-square-o" aria-hidden="true">&nbsp;</i><span class="d-none d-md-inline-block">Editar</span></a>);
                     }).WithPaging(10).Sortable(true).WithGridItemsCount("Registros encontrados").EmptyText("No se encontraron registros")
        </div>

    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        $(document).on('ready', function () {
            $('#btnsubmit').removeClass('disabled');
        });

        $(document).on("submit", "form",function () {
            var submited = parseInt($("#Submited").val());
            $(this).submit(function () {
                if (submited > 0) {
                    return false;
                }
                return true;
            });
            $("#Submited").val(submited + 1);
            return true;
        });

        $(document).on("change", '#I_TipoPeriodoID', function (event) {
            let txtPrioridad = $('#I_Prioridad');
            let cmbCtaDepositoHabilitadas = $('#cmbCuentasHabilitadas');
            let cmbCtaDeposito = $('#Arr_CtaDepositoID');

            txtPrioridad.val('');
            cmbCtaDepositoHabilitadas.empty();
            cmbCtaDeposito.empty();

            $.ajax({
                url: ('/api/Service/GetPrioridad/' + this.value),
                type: 'GET',
                contentType: 'application/json; charset=utf-8',
                dataType: 'json',
                cache: false,
                beforeSend: function () { },
                success: function (data) {
                    if (data && !isNaN(data)) {
                        txtPrioridad.val(data);
                    }
                },
                error: function () { },
                complete: function () { }
            });

            $.ajax({
                url: ('/api/Service/GetCuentasDeposito/' + this.value),
                type: 'GET',
                contentType: 'application/json; charset=utf-8',
                dataType: 'json',
                cache: false,
                beforeSend: function () { },
                success: function (data) {
                    if (data && data.length > 0) {
                        for (let i = 0; i < data.length; i++) {
                            cmbCtaDepositoHabilitadas.append('<option value="' + data[i].Value + '">' + data[i].TextDisplay + '</option>');
                        }
                    }
                },
                error: function () { },
                complete: function () { }
            });
        });

        $(document).on("click", "#btnAddCtaDeposito", function () {
            let comboOrigen = $('#cmbCuentasHabilitadas option:selected');
            let comboDestino = $('#Arr_CtaDepositoID');

            if (comboOrigen.length > 0) {
                for (var i = 0; i < comboOrigen.length; i++) {
                    let option = comboOrigen[i];

                    if (option.selected && !opcionDuplicada(comboDestino, option.value)) {
                        agregarOpcionCombo(comboDestino, option.value, option.text);
                    }
                }
            }
        });

        $(document).on("click", "#btnRemoveCtaDeposito", function () {
            $('#Arr_CtaDepositoID option:selected').remove();
        });

        function opcionDuplicada(comboBox, searchedValue) {
            if (comboBox[0].options.length > 0) {
                let options = comboBox[0].options;

                for (var i = 0; i < options.length; i++) {
                    let option = options[i];

                    if (option.value == searchedValue) {
                        return true;
                    }
                }
            }
            return false;
        }

        function agregarOpcionCombo(comboBox, id, text) {
            comboBox.append('<option value="' + id + '">' + text + '</option>');
        }
    </script>
}

src/app/00043-CuentasPorCobrar/WebApp/Views/Periodos/_MantenimientoPeriodo.cshtml
@model WebApp.ViewModels.MantenimientoPeriodoViewModel

<div class="modal-header bg-dark-gray" style="border-radius: .2rem .2rem 0px 0px">
    <h5 class="modal-title text-center"><i class="fa fa-address-book">&nbsp;</i> @ViewBag.Title</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
</div>
@using (Ajax.BeginForm("Save", "Periodos", new { area = "" }, new AjaxOptions { HttpMethod = "POST", InsertionMode = InsertionMode.Replace, UpdateTargetId = "div_msg", OnBegin = "Load", OnComplete = "Stop" }))
{
    @Html.Hidden("Submited", 0)
    @Html.AntiForgeryToken()
    <div class="modal-body">
        <div class="container-fluid">
            <fieldset>
                <legend><i class="fa fa-address-book-o">&nbsp;</i>Datos de la cuenta</legend>
                @Html.HiddenFor(model => model.I_PeriodoID)
                @Html.HiddenFor(model => model.B_Habilitado)

                <div class="form-group row">
                    @Html.LabelFor(model => model.I_TipoPeriodoID, new { @class = "col-md-3" })
                    <div class="col-md-8">
                        @Html.DropDownListFor(model => model.I_TipoPeriodoID, new SelectList(ViewBag.Lista_TipoPeriodo, "Value", "TextDisplay"), "[ SELECCIONAR ]", new { @class = "form-control" })
                        <p class="text-danger small">@Html.ValidationMessageFor(model => model.I_TipoPeriodoID)</p>
                    </div>
                </div>
                <div class="form-group row">
                    @Html.LabelFor(model => model.I_Anio, new { @class = "col-md-3" })
                    <div class="col-md-8">
                        @Html.DropDownListFor(model => model.I_Anio, new SelectList(ViewBag.Lista_Anios), "[ SELECCIONAR ]", new { @class = "form-control" })
                        <p class="text-danger small">@Html.ValidationMessageFor(model => model.I_Anio)</p>
                    </div>
                </div>
                <div class="form-group row">
                    @Html.LabelFor(model => model.D_FecVencto, new { @class = "col-md-3" })
                    <div class="col-md-8">
                        <div class='input-group date' id='datepicker_fecvento'>
                            @Html.TextBoxFor(model => model.D_FecVencto, "{0:dd/MM/yyyy}", new { @class = "form-control" })
                            <span class="input-group-addon"><i class="fa fa-calendar-o"></i></span>
                            <p class="text-danger small">@Html.ValidationMessageFor(model => model.D_FecVencto)</p>
                        </div>
                    </div>
                </div>
                <div class="form-group row">
                    @Html.LabelFor(model => model.I_Prioridad, new { @class = "col-md-3" })
                    <div class="col-md-8">
                        @Html.TextBoxFor(model => model.I_Prioridad, new { @class = "form-control", @readonly = "readonly" })
                        <p class="text-danger small">@Html.ValidationMessageFor(model => model.I_Prioridad)</p>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-md-3">Cuentas Habilitadas</label>
                    <div class="col-md-8">
                        @Html.DropDownList("cmbCuentasHabilitadas", new SelectList(ViewBag.Lista_CtaDepoHabilitadas, "Value", "TextDisplay"), new { @class = "form-control", @multiple = "multiple" })
                    </div>
                    <div class="col-md-1">
                        <button id="btnAddCtaDeposito" type="button" class="btn btn-link"><i class="fa fa-plus-circle"></i></button>
                    </div>
                </div>
                <div class="form-group row">
                    @Html.LabelFor(model => model.Arr_CtaDepositoID, new { @class = "col-md-3" })
                    <div class="col-md-8">
                        @Html.DropDownListFor(model => model.Arr_CtaDepositoID, new SelectList(ViewBag.Lista_CtaDepoPeriodo, "Value", "TextDisplay"), new { @class = "form-control", @multiple = "multiple" })
                        <p class="text-danger small">@Html.ValidationMessageFor(model => model.Arr_CtaDepositoID)</p>
                    </div>
                    <div class="col-md-1">
                        <button id="btnRemoveCtaDeposito" type="button" class="btn btn-link"><i class="fa fa-trash-o"></i></button>
                    </div>
                </div>
            </fieldset>
        </div>

    </div>

    <div class="modal-footer" id="div_msg">
        <div class="col-md-12" style="display:none" id="loading">
            <h6>Actualizando los datos...</h6>

            <div class="progress">
                <div class="indeterminate"></div>
            </div>
        </div>

        <button type="submit" class="btn btn-primary" id="btnsubmit"><i class="fa fa-save"></i>&nbsp;Guardar</button>
        <button type="button" class="btn btn-secondary" id="btnCancel" data-dismiss="modal"><i class="fa fa-times-circle-o">&nbsp;</i>Cancelar</button>
    </div>

    <script>
        $('#datepicker_fecvento').datepicker({
            todayBtn: 'linked',
            language: 'es',
            format: 'dd/mm/yyyy',
            autoclose: true,
            weekStart: 0,
            calendarWeeks: true
        }).on('hide', function (e) {
            e.stopPropagation();
        });

        $('form').submit(function () {
            $('#Arr_CtaDepositoID option').prop('selected', true);
        });
    </script>
}